@startuml sprzet

	class "Etykieta" as ETY {
		- nazwa : String
		- marka : Marka
		- opis : String
		- kategoria : Kategoria
		- sprzety : Set<Sprzet>
		- cenaZaDzien : double
		- cenaZaWyporzyczenie : double 
		- cenaZaOpoznienie : double
		- cenaZaOpoznienieZaDzien : double
	}

	class "Marka" as MAR {
		- nazwa : String
		- etykiety : Set<Etykieta>
	}

	class "Kategoria" as KAT {
		- nazwa : String
		- etykiety : Set<Etykieta>
		- cenaZaDzien : double
		- cenaZaWyporzyczenie : double
		- cenaZaOpoznienie : double
		- cenaZaOpoznienieZaDzien : double
	}

	class "Sprzet" as SPR {
		- id : int
		- dniEksploatacji : int
		- etykieta : Etykieta
		- status : SprzetStatus
		- wypozycenie : Optional<Wypozycenie>
		- wypozycenia : Set<Wypozycenie>
		- {static} domyslnaCenaZaDzien : double
		- {static} domyslnaCenaZaWyporzyczenie : double
		- {static} domyslnaCenaZaOpoznienie : double
		- {static} domyslnaCenaZaOpoznienieZaDzien : double
	}

	enum "SprzetStatus" as SPS {
		W_DRODZE_DO_OPERATORA
		W_MAGAZYNIE
		CZEKA_NA_WYDANIE_KLIENTOWI
		CZEKA_NA_WYDANIE_MAGAZYNIEROWI
		W_DRODZE_DO_MAGAZYNU
		W_NAPRAWIE
		WYPOZCONY
	}


	class "Wypozycenie" as WYP {
		- start : Date
		- end : Date
		- wplacono : double
		- doZaplaty : double
		- sprzet : Sprzet
		- klient : Klient
		- status : WypozycenieStatus
	}

	enum "WypozycenieStatus" as WYS {
		REZERWACJA
		W_TRAKCIE
		OPLACONE
		NIE_OPLACONE
		PRZEKROCZONO_TERMIN
	}




	class "Admin" as ADM {
		- login : String
		- haslo : String
		+ sprawdzHaslo(String) : boolean

		+ ustawCeneZaDzienDlaKategorii(Kategoria, double) : void
		+ ustawCeneZaDzienDlaEtykiety(Etykieta, double) : void
		+ ustawCeneDomyslnaZaDzien(double) : void
		+ ustawCeneZaWypozycenieDlaKategorii(Kategoria, double) : void
		+ ustawCeneZaWypozycenieDlaEtykiety(Etykieta, double) : void
		+ ustawCeneDomyslnaZaWypozycenie(double) : void

		+ ustawCenaZaOpoznienieDlaKategorii(Kategoria, double) : double
		+ ustawCenaZaOpoznienieZaDzienDlaKategorii(Kategoria, double) : double
		+ ustawCenaZaOpoznienieDlaEtykiety(Etykieta, double) : double
		+ ustawCenaZaOpoznienieZaDzienDlaEtykiety(Etykieta, double) : double
		+ ustawCenaDomyslnaZaOpoznienie(double) : double
		+ ustawCenaDomyslnaZaOpoznienieZaDzien(double) : double

		+ dodajSprzet(Etykieta, int) : void
		+ dodajEtykiete(Etykieta) : void
		+ dodajMarke(Marka) : void
		+ dodajKategorie(Kategoria) : void

		+ dodajPracownika(Pracownik) : void
	}

	class "Pracownik" as PRA {
		- imie : String
		- nazwisko : String
		- nrTel : String
		- dokument : String
		- stanowisko : String
		+ sprawdzHaslo(String) : boolean
	}

	class "Klient" as KLI {
		- imie : String
		- nazwisko : String
		- dokument : String
		- email : String
		- haslo : String
		- nrTel : Optional<String>
		- adres : Optional<String>
		- blokada : Date
		- wypozycenia : Set<Wypozycenie>
		- platnosci : Set<Platnosc>
		- wnioseki : Set<Wniosek>
		+ sprawdzHaslo(String) : boolean
		+ zablokuj(Date) : void
		+ oplac(Wypozycenie) : void
	}

	class "Magazynier" as MAG {
		- przyjeteZleceia : Set<Zlecenie>
		+ przyjmijZlecenie(Zlecenie) : void
		+ zrealizujZlecenie(Zlecenie) : void
	}

	class "PracownikBiurowy" as PBI {
		+ dodajKlienta(Klient) : void
		+ wydajSprzet(Klient, Sprzet) : void
		+ przyjmijSprzet(Klient, Sprzet) : void
	}

	class "Platnosc" as PLA {
		- data : Date
		- wypozycenie : Wypozycenie
		- kwota : double
	}

	class "Wniosek" as WNI {
		- nowaData : Date
		- klient : Klient
		- wypozycenie : Wypozycenie
		- status : WniosekStatus
		+ rozpatrz(boolean) : void
		+ rozpatrz(Date) : void
	}

	enum "WniosekStatus" as WNS {
		NIEROZPATRZONY
		ROZPATRZONY_POZYTYWNIE
		ROZPATRZONY_NEGATYWNIE
		ROZPATRZONY_CZESCIOWO_POZYTYWNIE
	}

	class "Zlecenie" as ZLE {
		- status : ZlecenieStatus
		- sprzet : Sprzet
	}
 
	enum "ZlecenieStatus" as ZLS {
		WYDANIE
		ODBIOR
	}

	SPR o--o ETY

	ETY o--o MAR

	ETY o--o KAT

	SPR o--o WYP

	WYS --o WYP

	KLI o--o WYP

	ADM -- PBI

	PBI -- KLI

	KLI o-- PLA
	PBI -- PLA
	PLA o-- WYP

	WNI o--o KLI
	WNI -- PBI
	WNI o-- WYP
	WNS --o WNI

	MAG --|> PRA
	PBI --|> PRA

	SPS --o SPR

	ZLS --o ZLE
	ZLE -- MAG
	ZLE --o SPR
	MAG -- SPR

@enduml